apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/kubernetes-id: my-kubernetes-component
    backstage.io/kubernetes-label-selector: app=my-dep
  name: my-kubernetes-component
spec:
  lifecycle: production
  owner: my-team
  type: service
